development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: shouldisendthis
  :password: 4four@dbc
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: shouldisendthis
  :password: 4four@dbc
  :enable_starttls_auto: true
