# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a4f17646ce47f48aa61b838b1a9ada40d3bae099fbb3007e70149a688e9318b8d149bc9a1557e0c7f5c1020deecf9cf280728bc29852dafcf374b7075f36ef2

test:
  secret_key_base: b9af674d7b2015debeb1de03748a99c9ca1055e968e4d6ed2f361cffb3a36834a16a17b8faac0c85caccb0221e5aa4e5af057c715365389c7de35b2b5aeeee56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
